title: <p align="center"> Mujib Sukri </p>
logo: "https://github.com/nurastars/Portfolio/blob/main/image.png?raw=true" #your photo (or logo) here

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  <a href="https://github.com/chriskhanhtran">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing ethical philosophy in artificial intelligence and data science.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
